import Head from 'next/head'
import Image from 'next/image'

import BgTest from '../components/BgTest'

import { useState } from 'react'
import Dropback from '../components/Dropback'
import Sidemenu from '../components/Sidemenu'

export default function Home() {
  const [open, setOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Dropback open={open} setOpen={setOpen} />
      <Sidemenu open={open} setOpen={setOpen} />

      <BgTest
        color={'#838383'}
        heading={'Grey'}
        nav
        open={open}
        setOpen={setOpen}
      />
      <BgTest color={'#03070E'} heading={'Low Black'} />
      <BgTest color={'#6269A8'} heading={'Mid Blue'} />
    </>
  )
}
